### ISSUE TITLE
Issues due to eval() 

### ISSUE THREAD

**Issue by PixelRBN** [PixelRBN/PyCalc#2]
### I found 2 issues due to `eval` function 
1. Leading zeros cause a error 
2. Mixed operators cause errors eg: `65+*6`

For the 1st issue I have tried this 
At line `347` in main.py
```
    if py_text[:1] not in op_sym:
        for s in op_sym:
            if s in py_text:
                print(py_text.split(s))
            print(py_text)
```

**Comment by Suryasai369** [comment]
For the first issue, you can try for loop for deleting leading zeros.
`for i in range(len({your_number})):
    if i!=0:
        {your_number}={your_number}[i:]
        break`

For second issue, you can also check for 2 operators side by side by using loop and if operators are in like that way, error should be raised.

`for i in range(len({your_number})-1):
    if ({your_number}[i] in {operators_array}) and ({your_number}[i+1] in {operators_array}):
        #raise Expection{try to warn user}`

I hope this helps.
